Repository sanic-org/sanic, pull requests merged in 2020-06, with the labels that each got.

#1827 Fix reloader on OSX py38 and Windows
  sanic/app.py
  sanic/reloader_helpers.py
  tests/test_reloader.py
Labels: breaking

#1857 fix-#1856: adjust websockets version to setup.py and make nightly (py39) tests pass
  sanic/websocket.py
  setup.py
  tests/test_reloader.py
  tox.ini
Labels: necessary

#1739 Deprecate body_bytes to merge into body
  sanic/response.py
  tests/test_response.py
Labels: on hold

#1641 Socket binding implemented properly for IPv6 and UNIX sockets.
  docs/sanic/deploying.rst
  examples/delayed_response.py
  sanic/__main__.py
  sanic/app.py
  sanic/asgi.py
  sanic/request.py
  sanic/server.py
  tests/test_requests.py
  tests/test_unix_socket.py
Labels: needs review
