Repository sanic-org/sanic, pull requests merged in 2021-11, with the labels that each got.

#2307 Provide list of reloaded files
  sanic/reloader_helpers.py
Labels: needs review

#2310 More consistent config setting with post-FALLBACK_ERROR_FORMAT apply
  sanic/app.py
  sanic/config.py
  sanic/errorpages.py
  sanic/mixins/routes.py
  sanic/router.py
  tests/test_config.py
  tests/test_errorpages.py
Labels: needs review, release-needed

#2268 Make HTTP connections start in IDLE stage, avoiding delays and error messages
  sanic/http.py
  tests/test_request_timeout.py
  tests/test_timeout_logic.py
Labels: bug, necessary, needs review, release-needed

#2260 Allow early Blueprint registrations to still apply later added objects
  sanic/app.py
  sanic/blueprints.py
  sanic/models/futures.py
  tests/test_blueprint_copy.py
  tests/test_blueprints.py
Labels: needs review

#2290 Add contextual exceptions
  sanic/errorpages.py
  sanic/exceptions.py
  tests/test_exceptions.py
Labels: needs review

#2305 Fix examples to work as expected
  examples/add_task_sanic.py
  examples/amending_request_object.py
  examples/authorized_sanic.py
  examples/blueprint_middlware_execution_order.py
  examples/blueprints.py
  examples/delayed_response.py
  examples/exception_monitoring.py
  examples/hello_world.py
  examples/http_redirect.py
  examples/limit_concurrency.py
  examples/log_request_id.py
  examples/logdna_example.py
  examples/run_asgi.py
  examples/run_async.py
  examples/run_async_advanced.py
  examples/simple_async_view.py
  examples/try_everything.py
  examples/unix_socket.py
  examples/url_for_example.py
  examples/versioned_blueprint_group.py
  examples/websocket.py
  sanic/mixins/routes.py
  sanic/models/futures.py
  tests/test_worker.py
Labels: needs review
