Repository sanic-org/sanic, pull requests merged in 2022-01, with the labels that each got.

#2354 Add config.update support for setters
  .github/workflows/codeql-analysis.yml
  .github/workflows/coverage.yml
  .github/workflows/pr-bandit.yml
  .github/workflows/pr-docs.yml
  .github/workflows/pr-linter.yml
  .github/workflows/pr-python310.yml
  .github/workflows/pr-python37.yml
  .github/workflows/pr-python38.yml
  .github/workflows/pr-python39.yml
  .github/workflows/pr-type-check.yml
  .github/workflows/pr-windows.yml
  sanic/config.py
  tests/test_config.py
  tests/test_errorpages.py
  tests/test_pipelining.py
  tests/test_server_loop.py
Labels: release-needed

#2355 Ignore name argument on Python 3.7
  .github/workflows/pr-type-check.yml
  sanic/app.py
  tests/test_create_task.py
Labels: release-needed

#2349 Only display MOTD in ASGI on startup
  sanic/app.py
Labels: release-needed

#2347 Sanic multi-application server
  .github/workflows/coverage.yml
  sanic/app.py
  sanic/application/state.py
  sanic/cli/app.py
  sanic/mixins/runner.py
  sanic/models/server_types.py
  sanic/reloader_helpers.py
  sanic/request.py
  sanic/server/protocols/base_protocol.py
  sanic/server/protocols/http_protocol.py
  sanic/server/protocols/websocket_protocol.py
  sanic/server/runners.py
  sanic/touchup/schemes/ode.py
  sanic/worker.py
  tests/conftest.py
  tests/test_app.py
  tests/test_cli.py
  tests/test_config.py
  tests/test_exceptions.py
  tests/test_motd.py
  tests/test_multi_serve.py
  tests/test_multiprocessing.py
  tests/test_prepare.py
  tests/test_server_events.py
  tests/test_tasks.py
  tests/test_unix_socket.py
  tests/test_worker.py
  tox.ini
Labels: needs review, breaking

#2366 fix: websocket dependency for websockets 9.1 security fix
  .github/workflows/codeql-analysis.yml
  .github/workflows/coverage.yml
  .github/workflows/on-demand.yml
  .github/workflows/pr-bandit.yml
  .github/workflows/pr-docs.yml
  .github/workflows/pr-linter.yml
  .github/workflows/pr-python-pypy.yml
  .github/workflows/pr-python37.yml
  .github/workflows/pr-python38.yml
  .github/workflows/pr-python39.yml
  .github/workflows/pr-type-check.yml
  .github/workflows/pr-windows.yml
  .github/workflows/publish-images.yml
  .github/workflows/publish-package.yml
  CHANGELOG.rst
  sanic/__version__.py
  sanic/compat.py
  sanic/request.py
  setup.py
  tests/test_asgi.py
  tests/test_config.py
  tests/test_logging.py
  tests/test_requests.py
  tox.ini
Labels: urgent
